inherit_from: [configs/dataset/config_base_3RScan_full_l20.yaml,configs/method/config_base_3DSSG_FAN.yaml]
model:
 multi_rel: false # multiple relationship 
wandb:
 tags: ["ssg", "3dssg","full","l20"]
